### ISSUE TITLE
Perform final configuration update for 11/5 Hotfire operations.

### ISSUE THREAD

**Issue by harrisonCassar** [UCLA-Rocket-Project/AresSoftware#27]
# Motivation/Description
There's a few changes that need to be made to the source code to support exact system requirements for supporting Propulsion's Hotfire on 11/5. This includes:
- Have ADC actually poll 10 channels (we need 1 more than what's currently implemented with #7 due to Load Cell needing a channel as well).
- Final ADC channel datastream label update:
    - IN0: LOx Fill
    - IN1: Fuel Tank
    - IN2: CC
    - IN3: Low Press
    - IN4: LOx Tank
    - IN5: LOx Manifold
    - IN6: Pneumatics
    - IN7: Fuel Manifold
    - IN8: High Press
    - IN9: Load Cell
- Final TC channel datastream label update:
    - 1: LOx Tank Top (Probe)
    - 2: LOx Tank Bottom (Probe)
    - 3: -
    - 4: Chamber (Patch)
    - 5: - 
- Final controls channel datastream label updates

# Work To Be Done
Check with Propulsion for the above labels, and perform the update accordingly.

Related to #10.

**Comment by philipdoucla** [comment]
Is this ready to be closed or is there something else we need to do?

**Comment by philipdoucla** [comment]
Ready for closure; Hotfire operations completed in adequate fashion.

~TRC 1/23/23
