### ISSUE TITLE
Establish standardized set of labels for GitHub Issues

### ISSUE THREAD

**Issue by harrisonCassar** [UCLA-Rocket-Project/AresSoftware#5]
The default set provided by GitHub are okay, but we can do better.

Pulling on our knowledge from industry, let's make a better-encompassing set!

**Comment by harrisonCassar** [comment]
Added a variety of different issue labels that encompass most of all we'll need. If additional use cases that aren't covered by this set arise, labels can be made at a later point.

![image](https://user-images.githubusercontent.com/43802050/198928684-afb73615-e2f9-4b9b-9de1-e6f770e68566.png)

Additionally, modified all currently-open issues to conform to this set of labels.

Passing off to @philipdoucla for concurrence for closure.

**Comment by philipdoucla** [comment]
Labeled!
